version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 150
    labels:
      - dependencies
    groups:
      angular:
        applies-to: version-updates
        patterns:
        - "@angular*"
        update-types:
        - "minor"
        - "patch"
      onecx:
        applies-to: version-updates
        patterns:
        - "@onecx*"
        update-types:
        - "minor"
        - "patch"
  - package-ecosystem: npm
    directory: "/test-deps/project1"
    schedule:
      interval: daily
    open-pull-requests-limit: 150
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: "/test-deps/project2"
    schedule:
      interval: daily
    open-pull-requests-limit: 150
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: "/test-deps/project3"
    schedule:
      interval: daily
    open-pull-requests-limit: 150
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: "/test-deps/project4"
    schedule:
      interval: daily
    open-pull-requests-limit: 150
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: "/test-deps/project5"
    schedule:
      interval: daily
    open-pull-requests-limit: 150
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: "/test-deps/project6"
    schedule:
      interval: daily
    open-pull-requests-limit: 150
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: "/test-deps/project7"
    schedule:
      interval: daily
    open-pull-requests-limit: 150
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: "/test-deps/project8"
    schedule:
      interval: daily
    open-pull-requests-limit: 150
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: "/test-deps/project9"
    schedule:
      interval: daily
    open-pull-requests-limit: 150
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: "/test-deps/project10"
    schedule:
      interval: daily
    open-pull-requests-limit: 150
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: "/test-deps/project11"
    schedule:
      interval: daily
    open-pull-requests-limit: 150
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: "/test-deps/project12"
    schedule:
      interval: daily
    open-pull-requests-limit: 150
    labels:
      - dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: daily
    labels:
      - docker-image